### PR TITLE
Cleanup formatting, use more modern Java, fix serialization

### PR DESCRIPTION
**Pull request by pivmatt**
Each of these commits are intertwined with previous commits, so it didn't make sense to split these out into multiple PRs (even though four different things are occurring here).

Here, we:

- Cleanup some too-far-right code
- Undo previous commits downgrading code from Java 7 to Java 6 (bringing us back up to Java 7)
- Add a serialization fix for resolving classes (`protected Class<?> resolveClass(ObjectStreamClass desc)`)
- Add session class restoration fix using Tomcat 8+ style (`context.bind`)

These changes (hopefully) close/resolve/fix all open issues and PRs in the `session-managers` repository.

Note: the serialization changes need proper review from someone with actual Tomcat experience.  All tests pass, but these changes haven't been tested against live servers/applications.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pivmatt Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotalsoftware/session-managers&pullRequestId=8) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pivmatt Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotalsoftware/session-managers&pullRequestId=8)!

**Comment by jkonicki** [comment]
Thank you Matt.

**Comment by pivmatt** [comment]
👍

**Pull request merged**
