### PR TITLE
Use the configured session timeout and set it as the expire time for the redis key

### PR DESCRIPTION
**Pull request by kaiinkinen**
No version of the plugin currently sets the expire time for the session keys in Redis. This can cause the session store to fill up over time, unless the keys are cleaned up through some other process. 

This fix sets the timeout to the value as specified in tomcat and the web.xml.

This addresses the issue reported here: 
https://github.com/pivotalsoftware/session-managers/issues/9

### CODE REVIEW

**Comment by mballoni** [comment]
I've made some tests and the tomcat containers cleans up the session at the configured timeout.
 However it might be a good idea to also setup a timeout (maybe longer than the tomcat) in case of a disaster.
 What do you think?

**Comment by kaiinkinen** [comment]
OK, this test is done using one (or more) instances that share sessions? I'm wondering whether our problem could be related to the special case where sessions might linger in case we replace the existing nodes with new ones? If the sessions aren't active in the new instance, they most probably never get cleaned out either. 

Using the Redis TTL/expire as a safety measure sounds like a legit solution to the problem. In this case there should, however, be some configuration for the safety margin. We flush the sessions after every request to Redis, so for us the margin doesn't need to be big, but a more general case would probably warrant one.

**Comment by mballoni** [comment]
I haven't test with multiple instances, just one.
 I agree with you, this could be a safe mode for, as I said, a disaster situation where your nodes are down.

**Comment by mballoni** [comment]
By the way, the only limitation for this solution is the sessions set. Its contents will never expire so either we live with this caveat or we design a particular solution (if possible).

**Comment by kaiinkinen** [comment]
Is it strictly necessary to keep the list of available keys in a separate entry in Redis? Is it required to be transactionally correct for existing sessions? 
I'm not familiar enough with the internals of Tomcat to know how often this value is accessed, and is it always queries before accessing the actual stored session-object. At least in RedisStore the value is not read at session load. 

Would it be sufficient to do a scan at start, and keep a local cache of it in memory, and potentially having another thread occasionally update the cache through additional scan-requests?

Given the way the sessions seem to build up over time, I'm a bit worried what happens in the long run with the sessions-key, when we have a multitude of nodes talking to the same cache. 

I'm happy to add this implementation in a separate pull request, but only if it is deemed a good enough solution, and not leading to severe performance problems.

**Comment by mballoni** [comment]
Scan might not be a good choice due to future cluster support (I'm working on it right now).
 Also scan usually perform interruption at the redis server creating a potential performance bottleneck.

 Maybe we could think of a solution that wouldn't demand the entire key set, to be honest I havn't thought about it much yet.

**Comment by jkonicki** [comment]
Thank you for the contribution.  Merged.

**Pull request merged**
